---
## docker install via galaxy@ansible.com
## by @tfindelkind

- name: Run playbook of geerlingguy.docker
  hosts: localhost
  user: centos
  connection: local # or ssh or paramiko

  tasks:
      - name: create group docker
      - shell:  sudo groupadd docker

      - name: add user centos to group docker
      - shell: sudo usermod -aG docker centos 

  roles:
      - geerlingguy.docker
