---
## docker install via galaxy@ansible.com
## by @tfindelkind

- name: Run playbook of geerlingguy.docker
  hosts: localhost
  user: centos
  connection: local # or ssh or paramiko

  tasks:
      - shell: ansible-galaxy install geerlingguy.docker

  roles:
      - geerlingguy.docker
